package ru.online.domain.command;

public enum CommandType {

    LS,
    DUMMY,
    MK_DIR,
    REM_DIR,
    UPLOAD,
    UPLOAD_READY,
    UPLOAD_COMPLETE,
    DOWNLOAD,
    DOWNLOAD_READY,
    DOWNLOAD_COMPLETE,
    REGISTRATION_REQUEST,
    REGISTRATION_SUCCEEDED,
    REGISTRATION_FAILED,
    AUTH_REQUEST,
    AUTH_SUCCEEDED,
    AUTH_FAILED


}
